### PR TITLE
Rename modules top level directory

### PR DESCRIPTION
**Pull request by wbamberg**
This is part of a fix for https://github.com/mdn/content/issues/14677. It would need corresponding updates in (only, AFAICT) https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules.

@Rumyra , I'm not sure if we want to do this. But if we don't, we should close https://github.com/mdn/content/issues/14677 as WONTFIX.

(I think we probably should, but don't feel very strongly either way.)

### CODE REVIEW

**Comment by Rumyra** [comment]
Yeh - I'm happy with `module-examples` as it's more explicit - but I also think we should have a content update at least in the works before merging 👍

**Comment by wbamberg** [comment]
> Yeh - I'm happy with `module-examples` as it's more explicit - but I also think we should have a content update at least in the works before merging 👍

I just filed https://github.com/mdn/content/pull/15934 for the other half of this.

**Comment by mohsinulhaq** [comment]
https://github.com/mdn/js-examples/blob/master/module-examples/README.md
Hi, it seems that we missed updating the GitHub Pages link here. :)

**Comment by wbamberg** [comment]
> https://github.com/mdn/js-examples/blob/master/module-examples/README.md Hi, it seems that we missed updating the GitHub Pages link here. :)

Ooops, thank you for letting me know. Filed https://github.com/mdn/js-examples/pull/19. Why do we have 2 READMEs here??

**Comment by mohsinulhaq** [comment]
I think this readme is supposed to be specifically regarding JS modules, and MDN directly links to this folder on GitHub: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

**Comment by wbamberg** [comment]
Fair enough. It should be fixed now anyway :).

**Comment by mohsinulhaq** [comment]
Thanks!

**Pull request merged**
