### PR TITLE
top level await example updated with await keyword

### PR DESCRIPTION
**Pull request by xkeshav**
in top level example file; update syntax with top level **await**

### CODE REVIEW

**Comment by xkeshav** [comment]
any update here ?

**Comment by bsmth** [comment]
Hi @xkeshav sorry I missed this one, I'm going through repositories to see if there's anything we overlooked. @Josh-Cena are you interested in having a look?

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
Hello, unfortunately this change is anti-performance and unnecessary. We are using import on demand on purpose, and even if we don't, we will be using static imports instead of `await import(...)` at the top level, which you should virtually never do. If you check out the [accompanying content text](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#top_level_await):

> Then we'll create a module called [getColors.js](https://github.com/mdn/js-examples/blob/main/module-examples/top-level-await/modules/getColors.js) which uses a fetch request to load the [colors.json](https://github.com/mdn/js-examples/blob/main/module-examples/top-level-await/data/colors.json) file and return the data as an object.

The top level await is actually in the `getColors.js` file.

**Comment by bsmth** [comment]
Thanks a lot for chiming in, Josh. @xkeshav I hope that clarifies things for you. I'm going to close this PR now but if you have some more questions of if you think there's a mistake, please let us know here. Thank you :)

**Comment by xkeshav** [comment]
Got it. Thank you for the detailed explanation.

**Pull request closed without merging**
